# Generated by Django 4.1.5 on 2023-01-05 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('f_name', models.CharField(default='', max_length=64)),
                ('l_name', models.CharField(default='', max_length=64)),
                ('gender', models.CharField(default='', max_length=6)),
                ('email_id', models.EmailField(default='', max_length=254, unique=True)),
                ('edu_year', models.CharField(default='', max_length=4)),
                ('skill', models.JSONField()),
                ('edu_collage_name', models.CharField(default='', max_length=120)),
                ('edu_marks', models.CharField(blank=True, default='', max_length=9)),
                ('internship', models.CharField(blank=True, default='', max_length=2000)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='img/2023-01-05')),
                ('resume', models.FileField(default='', upload_to='resume/2023-01-05', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('apply_date', models.CharField(max_length=30)),
                ('hired', models.IntegerField(default=0)),
                ('interview', models.IntegerField(default=0)),
                ('assignment', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, unique=True)),
                ('text', models.CharField(max_length=6010)),
            ],
        ),
        migrations.CreateModel(
            name='EventDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meetUrl', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=6010)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('description', models.TextField(max_length=400)),
                ('experience', models.CharField(max_length=100)),
                ('location', models.JSONField()),
                ('skills', models.JSONField()),
                ('creation_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=1200)),
                ('answer', models.CharField(max_length=240)),
                ('option2', models.CharField(max_length=240)),
                ('option3', models.CharField(max_length=240)),
                ('option4', models.CharField(max_length=240)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
            ],
        ),
        migrations.CreateModel(
            name='Apply_candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('Applyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apply')),
            ],
        ),
        migrations.AddField(
            model_name='apply',
            name='jobid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job'),
        ),
    ]
